copyright: Copyright &copy;2022, Loyd Hook IV.

edit_uri: ""

extra:
  generator: false

markdown_extensions:
  - attr_list

nav:
  - Home: 'index.md'
  - Standards:
      - General: best_practises_software_development.md
      - Polynomial Multiplikation: polynomial_multiplication.md
      - Programming Languages:
          - C++: best_practises_cpp.md
          - Python:
            - Standards: best_practises_python.md
            - Implementation Example: implementation_python.md
  - Release Documents:
      - Release Notes: 'release_notes.md'
      - Release History: 'release_history.md'
  - Code of Conduct: 'code_of_conduct.md'
  - License: 'LICENSE.md'

plugins:
  - search

repo_url: https://github.com/FAA-VAIL-Project/sds

site_name: sds - Software Development Standards
# site_url: **TODO**
site_description: Software Development Standards
site_author: FAA-VAIL-Project Team

theme:
  favicon: img/Icon.png
  features:
    - search.highlight
    - search.suggest
  language: en
  logo: img/VAILLogo.png
  name: material
  palette:
    primary: blue
    accent: red

