copyright: Copyright &copy;2022, Loyd Hook IV.

edit_uri: ""

extra:
  generator: false
extra_css:
  - assets/pymdownx-extras/extra-b1466b3f51.css
extra_javascript:
  - https://unpkg.com/mermaid@8.13.3/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/pymdownx-extras/extra-loader-9e2c67b9.js

markdown_extensions:
  - attr_list
  - pymdownx.highlight
  - pymdownx.tilde
  - toc : {
    toc_depth: "1-3"
  }

nav:
  - Home: index.md
  - API Documentation: api_documentation.md

plugins:
  - autorefs
  - awesome-pages
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 3
            paths: [src/polynomial]
            show_root_heading: false
            show_source: true
  - search

repo_name: GitHub
repo_url: https://github.com/FAA-VAIL-Project/sds

site_name: sds - Software Development Standards
# site_url: **TODO**
site_description: Software Development Standards
site_author: FAA-VAIL-Project Team

theme:
  favicon: img/Icon.png
  features:
    - search.highlight
    - search.suggest
  language: en
  logo: img/VAILLogo.png
  name: material
  palette:
    primary: blue
    accent: red

use_directory_urls: false
